---
profiles:
  default:
    #NOTE: Enter your private key here
    private_key: "0xe80507ed864b9fa5343bae9504abc0f71baed8969abfa26a77a5512a48e64e20"
    #NOTE: Enter your public key here
    public_key: "0x4085614bac67f35aaa8843566633d3b05e182e53af02bad646e42cf734e68afd"
    #NOTE: Enter your account here
    account: 0x4085614bac67f35aaa8843566633d3b05e182e53af02bad646e42cf734e68afd
    rest_url: "https://fullnode.random.aptoslabs.com"
    faucet_url: "https://faucet.random.aptoslabs.com"
