[package]
name = "random_reward"
version = "1.0.0"
authors = []

[addresses]
my_management_addr='0x4c2356b3b505caa19ec9ef3745e35aa414cb81e9e0df9ed1fe83c4128f2fd2ed'


[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]
