[package]
name = "random_reward"
version = "1.0.0"
authors = []

[addresses]
my_management_addr='0xe1232f6fef99143c508b0036a0d046486e6d47e21a22c26384e1f320843f0b06'


[dev-addresses]


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-token-objects"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "randomnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dev-dependencies]
